version: '3.9'
services:
  java21db:
    image: "kartoza/postgis:13.0"
    restart: unless-stopped
    hostname: java21db
    domainname: java21db
    environment:
      POSTGRES_USER: java21dbuser
      POSTGRES_PASS: java21dbpass
      POSTGRES_DBNAME: java21casestudydb
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - "5432:5432"
    volumes:
      - java21db:/var
    networks:
      - java21-net
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
  java-21-demo-backend:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile2
      args:
        APP_FILE_NAME: java-21-demo
    pull_policy: never
    ports:
      - "8080:8080"
    environment:
      APP_FILE_NAME: java-21-demo
      DB_URL: jdbc:postgresql://java21db:5432/java21casestudydb
    depends_on:
      java21db:
        condition: service_healthy
    networks:
      - java21-net


networks:
  java21-net:
    driver: bridge

volumes:
  java21db:
