version: '3.9'
services:
  getirdb:
    image: "kartoza/postgis:13.0"
    restart: unless-stopped
    hostname: getirdb
    domainname: getirdb
    environment:
      POSTGRES_USER: getirdbuser
      POSTGRES_PASS: getirdbpass
      POSTGRES_DBNAME: getircasestudydb
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - "5432:5432"
    volumes:
      - getirdb:/var
    networks:
      - getir-net
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
#      interval: 30s
#      timeout: 60s
#      retries: 5
#      start_period: 80s
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
  getir-case-study-backend:
    restart: always
    build: src
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://getirdb:5432/getircasestudydb
    depends_on:
      getirdb:
        condition: service_healthy
    networks:
      - getir-net


networks:
  getir-net:
    driver: bridge

volumes:
  getirdb:
