spring:
  application:
    name: GetirCaseStudy
    description: Case Study for Getir Interview
  profiles:
    include: postgresql

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

logging:
  level:
    org.hibernate: INFO
    org.liquibase: INFO
