spring:
  application:
    name: JAVA21CaseStudy
    description: Case Study for JAVA 21 Demonstration
  profiles:
    include: postgresql
  thread-executor: virtual

springdoc:
  swagger-ui:
    path: /swagger-ui

security:
  jwtSecret: java21CaseStudy
  jwtExpirationMs: 86400000

server:
  port: 8080

logging:
  level:
    org.hibernate: INFO
    org.liquibase: INFO

