spring:
  application:
    name: GetirCaseStudy
    description: Case Study for Getir Interview
  profiles:
    include: postgresql
springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8080

security:
  jwtSecret: getirCaseStudy
  jwtExpirationMs: 86400000

logging:
  level:
    org.hibernate: INFO
    org.liquibase: INFO
