spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/getircasestudydb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:getirdbuser}
    password: ${DB_PASSWORD:getirdbpass}
    hikari:
      pool-name: GetirCaseStudyPostgresHikariPool
      maximum-pool-size: 10
      minimum-idle: 3
      connectionTimeout: 10000
      idle-timeout: 60000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        package_to_scan: com.getir.javacasestudy
  data:
    jpa:
      repositories:
        enabled: true
  liquibase:
    change-log: db/changelog/changelog-master.xml
    enabled: ${LIQUIBASE_ENABLED:true}